List listToSearch = [
  {'name': 'Tanger', 'class': 0},
  {'name': 'Agadir', 'class': 1},
  {'name': 'Al Hoceïma', 'class': 2},
  {'name': 'Assilah', 'class': 3},
  {'name': 'Azrou', 'class': 4},
  {'name': 'Beni Mellal', 'class': 5},
  {'name': 'Berkane', 'class': 6},
  {'name': 'Berrechid', 'class': 7},
  {'name': 'Bouznika', 'class': 8},
  {'name': 'Casablanca', 'class': 9},
  {'name': 'Chefchaouen ', 'class': 10},
  {'name': 'El Hajeb', 'class': 11},
  {'name': 'El Jadida', 'class': 12},
  {'name': 'Errachidia', 'class': 13},
  {'name': 'Essaouira', 'class': 14},
  {'name': 'Fès', 'class': 15},
  {'name': 'Ifrane', 'class': 16},
  {'name': 'Khémisset', 'class': 17},
  {'name': 'Khénifra', 'class': 18},
  {'name': 'Khouribga', 'class': 19},
  {'name': 'Larache', 'class': 20},
  {'name': 'Marrakech', 'class': 21},
  {'name': 'Meknès', 'class': 22},
  {'name': 'Nador', 'class': 23},
  {'name': 'Rabat', 'class': 24},
  {'name': 'Salé', 'class': 25},
  {'name': 'Safi ', 'class': 26},
];
